/*
 * litello
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-09-19T13:56:58Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Book
 */

public class Book {
  @SerializedName("id")
  private String id = null;

  @SerializedName("isbn")
  private String isbn = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("bookName")
  private String bookName = null;

  @SerializedName("creator")
  private String creator = null;

  @SerializedName("publisher")
  private String publisher = null;

  @SerializedName("tags")
  private String tags = null;

  @SerializedName("urlPreview")
  private String urlPreview = null;

  @SerializedName("epubUrlComplete")
  private String epubUrlComplete = null;

  @SerializedName("zipUrlComplete")
  private String zipUrlComplete = null;

  @SerializedName("urlCover")
  private String urlCover = null;

  @SerializedName("language")
  private String language = null;

  public Book id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Book isbn(String isbn) {
    this.isbn = isbn;
    return this;
  }

   /**
   * Get isbn
   * @return isbn
  **/
  @ApiModelProperty(value = "")
  public String getIsbn() {
    return isbn;
  }

  public void setIsbn(String isbn) {
    this.isbn = isbn;
  }

  public Book title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @ApiModelProperty(value = "")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Book bookName(String bookName) {
    this.bookName = bookName;
    return this;
  }

   /**
   * Get bookName
   * @return bookName
  **/
  @ApiModelProperty(value = "")
  public String getBookName() {
    return bookName;
  }

  public void setBookName(String bookName) {
    this.bookName = bookName;
  }

  public Book creator(String creator) {
    this.creator = creator;
    return this;
  }

   /**
   * Get creator
   * @return creator
  **/
  @ApiModelProperty(value = "")
  public String getCreator() {
    return creator;
  }

  public void setCreator(String creator) {
    this.creator = creator;
  }

  public Book publisher(String publisher) {
    this.publisher = publisher;
    return this;
  }

   /**
   * Get publisher
   * @return publisher
  **/
  @ApiModelProperty(value = "")
  public String getPublisher() {
    return publisher;
  }

  public void setPublisher(String publisher) {
    this.publisher = publisher;
  }

  public Book tags(String tags) {
    this.tags = tags;
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @ApiModelProperty(value = "")
  public String getTags() {
    return tags;
  }

  public void setTags(String tags) {
    this.tags = tags;
  }

  public Book urlPreview(String urlPreview) {
    this.urlPreview = urlPreview;
    return this;
  }

   /**
   * Get urlPreview
   * @return urlPreview
  **/
  @ApiModelProperty(value = "")
  public String getUrlPreview() {
    return urlPreview;
  }

  public void setUrlPreview(String urlPreview) {
    this.urlPreview = urlPreview;
  }

  public Book epubUrlComplete(String epubUrlComplete) {
    this.epubUrlComplete = epubUrlComplete;
    return this;
  }

   /**
   * Get epubUrlComplete
   * @return epubUrlComplete
  **/
  @ApiModelProperty(value = "")
  public String getEpubUrlComplete() {
    return epubUrlComplete;
  }

  public void setEpubUrlComplete(String epubUrlComplete) {
    this.epubUrlComplete = epubUrlComplete;
  }

  public Book zipUrlComplete(String zipUrlComplete) {
    this.zipUrlComplete = zipUrlComplete;
    return this;
  }

   /**
   * Get zipUrlComplete
   * @return zipUrlComplete
  **/
  @ApiModelProperty(value = "")
  public String getZipUrlComplete() {
    return zipUrlComplete;
  }

  public void setZipUrlComplete(String zipUrlComplete) {
    this.zipUrlComplete = zipUrlComplete;
  }

  public Book urlCover(String urlCover) {
    this.urlCover = urlCover;
    return this;
  }

   /**
   * Get urlCover
   * @return urlCover
  **/
  @ApiModelProperty(value = "")
  public String getUrlCover() {
    return urlCover;
  }

  public void setUrlCover(String urlCover) {
    this.urlCover = urlCover;
  }

  public Book language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @ApiModelProperty(value = "")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Book book = (Book) o;
    return Objects.equals(this.id, book.id) &&
        Objects.equals(this.isbn, book.isbn) &&
        Objects.equals(this.title, book.title) &&
        Objects.equals(this.bookName, book.bookName) &&
        Objects.equals(this.creator, book.creator) &&
        Objects.equals(this.publisher, book.publisher) &&
        Objects.equals(this.tags, book.tags) &&
        Objects.equals(this.urlPreview, book.urlPreview) &&
        Objects.equals(this.epubUrlComplete, book.epubUrlComplete) &&
        Objects.equals(this.zipUrlComplete, book.zipUrlComplete) &&
        Objects.equals(this.urlCover, book.urlCover) &&
        Objects.equals(this.language, book.language);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, isbn, title, bookName, creator, publisher, tags, urlPreview, epubUrlComplete, zipUrlComplete, urlCover, language);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Book {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isbn: ").append(toIndentedString(isbn)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    bookName: ").append(toIndentedString(bookName)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    publisher: ").append(toIndentedString(publisher)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    urlPreview: ").append(toIndentedString(urlPreview)).append("\n");
    sb.append("    epubUrlComplete: ").append(toIndentedString(epubUrlComplete)).append("\n");
    sb.append("    zipUrlComplete: ").append(toIndentedString(zipUrlComplete)).append("\n");
    sb.append("    urlCover: ").append(toIndentedString(urlCover)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

